version: 2.1
jobs:
  build:
    working_directory: ~/typescript-react-redux
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
          name: check-node-version
          command: 'node --version'
      - run:
          name: check-npm-version
          command: 'npm --version'
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5'
      - run:
          name: check-updated-npm-version
          command: 'npm --version'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: release
          command: npm run release
workflows:
  version: 2
  workflow:
    jobs:
    - build
